# Lyssna på port 1883, så att enheter i nätverket kan ansluta
listener 1883

# Kräv inloggning, ingen får ansluta anonymt
allow_anonymous false

# Filen med användarnamn och hashade lösenord
password_file C:\iot-sensor-system\src\broker\passwd